import React from 'react';
 import { Text, TouchableOpacity, View , NativeModules, Platform} from 'react-native';
 
 const App = () => {
   return (
     <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
       <TouchableOpacity onPress= {()=>{

         /// For all payment params please refre this link https://traknpaypg.docs.stoplight.io/request-param-list
         var options = {
          api_key: '<YOUR API KEY>',// Your Merchna t API KEY
          order_id: 'TEST5001',
          mode: 'LIVE',
          description: 'Test',
          currency: 'INR',
          amount: '2',
          name: 'Senthil',
          email: 'emailsenthil@test.com',
          phone: '9597403366',
          city: 'Chennai',
          state: 'Tamilnadu',
          country: 'IND',
          zip_code: '630501',
          address_line_1: 'ad1',
          address_line_2: 'ad2',
          interface_type: Platform.OS === 'ios' ? 'ios_sdk' : 'android_sdk', /// This is manadatory for UPI Intent payment
          return_url: 'http://localhost:8888/paymentresponse',
          hash: '<YOUR SERVER GNERATED HSH KEY>' // Hash Key which is generated by Sever end https://traknpaypg.docs.stoplight.io/architecture_explanation_and_Recommendations
        }

         NativeModules.RNPaymentGateway.open('<YOUR PAYMENT SEVER URL>', options)
          .then(res => {
            // This is success call response handling for ref https://traknpaypg.docs.stoplight.io/response-codes
            var obj = JSON.parse(res);
            console.log(obj);
            console.log(obj.response_code);
          })
          .catch(e => console.log(e.message, e.code))
       }}>
       <Text>
         Pay Now Button
       </Text>
       </TouchableOpacity>
     </View>
   );
 }
 
 export default App;